Exercise 23: Temperatures - graph cu eroare Add temperature C': 22 Exception in thread "main" java.lang.NoClassDefFoundError: org/jfree/util/PublicCloneable 	at java.lang.ClassLoader.defineClass1(Native Method) 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at week_1.Ex23_Temperatures.main(Ex23_Temperatures.java:12) Caused by: java.lang.ClassNotFoundException: org.jfree.util.PublicCloneable 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	... 13 more